---
- name: Reboot Ubuntu Servers
  hosts: ubuntu_servers_rtp
  become: true
  tasks:
    - name: Reboot the server
      ansible.builtin.reboot:
      when: hostvars[inventory_hostname]['reboot'] | default('false') | bool


