- name: Unconditionally reboot the machine with all defaults
  hosts: ubuntu-lab-all
  become: true
  #serial: 1 # one host at a time
  any_errors_fatal: true
  max_fail_percentage: 0
 
  tasks: # tasks are done in order


    - name: reboot
      reboot:




